-- Store session metadata and packet summaries only. Never store raw payloads.
create table if not exists public.capture_sessions (
    id bigint generated by default as identity primary key,
    interface_id text not null,
    interface_name text not null,
    status text not null,
    packet_count bigint not null default 0 check (packet_count >= 0),
    bytes_captured bigint not null default 0 check (bytes_captured >= 0),
    started_at timestamptz not null,
    ended_at timestamptz
);

create index if not exists capture_sessions_started_at_idx
    on public.capture_sessions (started_at desc);

create table if not exists public.packet_summaries (
    id bigint generated by default as identity primary key,
    session_id bigint not null references public.capture_sessions(id) on delete cascade,
    packet_index bigint not null check (packet_index > 0),
    packet_summary jsonb not null,
    unique (session_id, packet_index)
);

create index if not exists packet_summaries_session_idx
    on public.packet_summaries (session_id, packet_index);

alter table public.capture_sessions enable row level security;
alter table public.packet_summaries enable row level security;

-- The application uses its backend-only service role key. Do not put that key
-- in browser JavaScript. No anon/authenticated policies are created here.
grant all on public.capture_sessions to service_role;
grant all on public.packet_summaries to service_role;
grant usage, select on all sequences in schema public to service_role;
